documentation:
  - changed-files:
      - any-glob-to-any-file:
          - README.md
          - CONTRIBUTING.md
          - release/**/*.md
          - .github/ISSUE_TEMPLATE/**
          - .github/PULL_REQUEST_TEMPLATE/**
          - website/README.md
          - website/src/content/docs/**

dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - go.mod
          - go.sum
          - .github/renovate.json
          - website/package.json
          - website/pnpm-lock.yaml

test related:
  - changed-files:
      - any-glob-to-any-file:
          - "**/*_test.go"
          - testsuite/**
          - .github/workflows/testsuite-run.yml
          - .github/workflows/superfile-build-test.yml

theme:
  - changed-files:
      - any-glob-to-any-file:
          - asset/theme/**
          - src/superfile_config/theme/**

website:
  - changed-files:
      - any-glob-to-any-file:
          - website/**

new config:
  - changed-files:
      - any-glob-to-any-file:
          - src/config/**
          - src/superfile_config/config.toml

new hotkeys:
  - changed-files:
      - any-glob-to-any-file:
          - src/superfile_config/hotkeys.toml
          - src/superfile_config/vimHotkeys.toml

packaging:
  - changed-files:
      - any-glob-to-any-file:
          - Makefile
          - build.sh
          - flake.nix
          - flake.lock
          - gomod2nix.toml
          - release/**
          - asset/spf.desktop
          - .github/workflows/update-gomod2nix.yml
          - .github/workflows/winget.yml
