version: 1

before:
  hooks:
    - cd ./src && go mod tidy

builds:
  - main: ./src/main.go
    id: "superfile"
    binary: spf
    goos:
      - linux
      - darwin

archives:
  - format: tar.gz
    name_template: >-
      ./{{ .ProjectName }}_
      ./{{- title .Os }}_
      ./{{- if eq .Arch "amd64" }}x86_64
      ./{{- else if eq .Arch "386" }}i386
      ./{{- else }}{{ .Arch }}{{ end }}
      ./{{- if .Arm }}v{{ .Arm }}{{ end }}