schema = 3

[mod]
  [mod.'charm.land/bubbles/v2']
    version = 'v2.1.0'
    hash = 'sha256-2OmqpBrl+taOJzAhVM6OReLmoYRxZOXx9JqFNjQjsPA='

  [mod.'charm.land/bubbletea/v2']
    version = 'v2.0.2'
    hash = 'sha256-oWZTg8c3uM0oJfibwIGvh0PbBj6ikoxuk+/cZ4Jm924='

  [mod.'charm.land/lipgloss/v2']
    version = 'v2.0.3'
    hash = 'sha256-/RFkSUscU3NwymzT+PfizGf3XyQIdVGQlX7vxktCUGk='

  [mod.'github.com/Unpackerr/iso9660']
    version = 'v0.0.3'
    hash = 'sha256-2DFDOk39I8NGNy57F/J62Q23hFUxeAux92v51BlYKVo='

  [mod.'github.com/adrg/xdg']
    version = 'v0.5.3'
    hash = 'sha256-bo6tBgHS+3sl6f4oWpmdFrZjfV6eA/3xAlysSW0bIEs='

  [mod.'github.com/alecthomas/chroma/v2']
    version = 'v2.26.0'
    hash = 'sha256-iY5vB9N5lNQLubD/v0j5PsNo1890Un7b/HjhQBZBSkc='

  [mod.'github.com/andybalholm/brotli']
    version = 'v1.2.0'
    hash = 'sha256-EwPR3o6o8dUzsAeHki26rYm/s1uDuEcpV3ljmaHiNSg='

  [mod.'github.com/atotto/clipboard']
    version = 'v0.1.4'
    hash = 'sha256-ZZ7U5X0gWOu8zcjZcWbcpzGOGdycwq0TjTFh/eZHjXk='

  [mod.'github.com/aymanbagabas/go-osc52/v2']
    version = 'v2.0.1'
    hash = 'sha256-6Bp0jBZ6npvsYcKZGHHIUSVSTAMEyieweAX2YAKDjjg='

  [mod.'github.com/barasher/go-exiftool']
    version = 'v1.10.0'
    hash = 'sha256-ed+Jhji3usyMROzjw7Xq++khLz3mDrlgfn+vrBXWZgg='

  [mod.'github.com/bodgit/plumbing']
    version = 'v1.3.0'
    hash = 'sha256-nmLdJAB2sWpwHb2lFrYTcMR4yusMM1U629Pm2K9hfm0='

  [mod.'github.com/bodgit/sevenzip']
    version = 'v1.6.1'
    hash = 'sha256-2kT6kZsKnRBf20KkMCjtiu7IoOXxDjk+u9kYyrziaWA='

  [mod.'github.com/bodgit/windows']
    version = 'v1.0.1'
    hash = 'sha256-GSpAGboli54A5wDMpDEdZDYh55o1Zs8dZzFIf7hYdMY='

  [mod.'github.com/cavaliergopher/cpio']
    version = 'v1.0.1'
    hash = 'sha256-ezPCk5CzTZVnpgDVAp+djs2AyTqnHTLErvOWk0FdUS4='

  [mod.'github.com/cavaliergopher/rpm']
    version = 'v1.3.0'
    hash = 'sha256-Bc6mY7OuBw9WF6YLBNU+fvQyTEMm9chpjSKtPN+OPVY='

  [mod.'github.com/charmbracelet/colorprofile']
    version = 'v0.4.3'
    hash = 'sha256-y+QDUxGOKhugEMQLRUTZYT2C+wKqYHnMLJ44jbh7+JA='

  [mod.'github.com/charmbracelet/harmonica']
    version = 'v0.2.0'
    hash = 'sha256-fi5N0IXhSbbYHdSZFngCfpT4kdiEaKedqj8YpnlvX0o='

  [mod.'github.com/charmbracelet/lipgloss']
    version = 'v0.10.0'
    hash = 'sha256-JZD1iVeizYe0mp3qQcJbUZdYN6HP/DNC67ja79DTe6s='

  [mod.'github.com/charmbracelet/ultraviolet']
    version = 'v0.0.0-20260205113103-524a6607adb8'
    hash = 'sha256-zHe+nAS80nJPgZ4c3mU2HcHA9QL486b0BiyC4FNK3Nk='

  [mod.'github.com/charmbracelet/x/ansi']
    version = 'v0.11.7'
    hash = 'sha256-q8BZJq4K7NE5ETocN9/G/EoV0dUyD703ONSfHiUYzWQ='

  [mod.'github.com/charmbracelet/x/term']
    version = 'v0.2.2'
    hash = 'sha256-KF7IU1Luxl/sZP6XjomWB2e3lxSUS4/5AahhapGir/4='

  [mod.'github.com/charmbracelet/x/termios']
    version = 'v0.1.1'
    hash = 'sha256-sri3LpHCBhGvnJldDzBxwbbZpeSGZVCJFOUL45uBFds='

  [mod.'github.com/charmbracelet/x/windows']
    version = 'v0.2.2'
    hash = 'sha256-CvmE8kAC5wlPSeWjl2hc5xizvGS2FeOLHw84froldkk='

  [mod.'github.com/clipperhouse/displaywidth']
    version = 'v0.11.0'
    hash = 'sha256-WokyTaofEy95xlshqK5YDzpemhXV5oaQifxS9YyfCXo='

  [mod.'github.com/clipperhouse/uax29/v2']
    version = 'v2.7.0'
    hash = 'sha256-GO3az7WiGcwU0OvmocwdfR5ohGRL8NbjscIaMyhAdxE='

  [mod.'github.com/davecgh/go-spew']
    version = 'v1.1.2-0.20180830191138-d8f796af33cc'
    hash = 'sha256-fV9oI51xjHdOmEx6+dlq7Ku2Ag+m/bmbzPo6A4Y74qc='

  [mod.'github.com/disintegration/imaging']
    version = 'v1.6.2'
    hash = 'sha256-pSeMTPvSkxlthh65LjNYYhPLvCZDkBgVgAGYWW0Aguo='

  [mod.'github.com/dlclark/regexp2']
    version = 'v1.12.0'
    hash = 'sha256-PVX2rDCkiG0vyA1CbDi3bzLeZ2T8hcqJv3pZ5YwGzMI='

  [mod.'github.com/dlclark/regexp2/v2']
    version = 'v2.1.0'
    hash = 'sha256-AUF+0kL+e2txpBo+a/woYnCd44En/2giuDgpH3Gq3sw='

  [mod.'github.com/ebitengine/purego']
    version = 'v0.10.0'
    hash = 'sha256-NPS88SNvsm4QEAx1zVmNGzMwtR1EBhdQYywQU1JdRqM='

  [mod.'github.com/fatih/color']
    version = 'v1.18.0'
    hash = 'sha256-pP5y72FSbi4j/BjyVq/XbAOFjzNjMxZt2R/lFFxGWvY='

  [mod.'github.com/fvbommel/sortorder']
    version = 'v1.1.0'
    hash = 'sha256-553Rg/amloO6nv67p0ARsKas9QNnTQucpi08vNLtjQU='

  [mod.'github.com/go-ole/go-ole']
    version = 'v1.2.6'
    hash = 'sha256-+oxitLeJxYF19Z6g+6CgmCHJ1Y5D8raMi2Cb3M6nXCs='

  [mod.'github.com/google/uuid']
    version = 'v1.6.0'
    hash = 'sha256-VWl9sqUzdOuhW0KzQlv0gwwUQClYkmZwSydHG2sALYw='

  [mod.'github.com/hashicorp/golang-lru/v2']
    version = 'v2.0.7'
    hash = 'sha256-t1bcXLgrQNOYUVyYEZ0knxcXpsTk4IuJZDjKvyJX75g='

  [mod.'github.com/icza/bitio']
    version = 'v1.1.0'
    hash = 'sha256-CtV/dr1L46cZ65EnK9DrBduZCaMnTGf4N2MnElCymtM='

  [mod.'github.com/klauspost/compress']
    version = 'v1.18.4'
    hash = 'sha256-swwNE6xKz4ZAOUHPWFlHYiqFeZLRZuuKYhLQ34aYnAU='

  [mod.'github.com/kr/text']
    version = 'v0.2.0'
    hash = 'sha256-fadcWxZOORv44oak3jTxm6YcITcFxdGt4bpn869HxUE='

  [mod.'github.com/lazysegtree/go-zoxide']
    version = 'v0.1.0'
    hash = 'sha256-PKEV+zCKf/7MsFAMMctL/pFSnEsri1yS8Bzxcj1dLWE='

  [mod.'github.com/lithammer/shortuuid']
    version = 'v3.0.0+incompatible'
    hash = 'sha256-dD6ArCHGnpo84RBy6SI2kUjMqHS4IZU+K+DgAgmRakY='

  [mod.'github.com/lucasb-eyer/go-colorful']
    version = 'v1.4.0'
    hash = 'sha256-i/3GDHKEMLCy0kc3mtyk58UWYOPmKoUVaq6QCAWXKP0='

  [mod.'github.com/mattn/go-colorable']
    version = 'v0.1.13'
    hash = 'sha256-qb3Qbo0CELGRIzvw7NVM1g/aayaz4Tguppk9MD2/OI8='

  [mod.'github.com/mattn/go-isatty']
    version = 'v0.0.20'
    hash = 'sha256-qhw9hWtU5wnyFyuMbKx+7RB8ckQaFQ8D+8GKPkN3HHQ='

  [mod.'github.com/mattn/go-runewidth']
    version = 'v0.0.23'
    hash = 'sha256-SmChZ2U1aR8pW3LPhdM7KcVF5TO6VcHgRzBtUXbBWJA='

  [mod.'github.com/mewkiz/flac']
    version = 'v1.0.13'
    hash = 'sha256-cQ10kMBZGiw7O0+cDW+Hr2LQVZbn1mM+op0vYIsR6sw='

  [mod.'github.com/mewkiz/pkg']
    version = 'v0.0.0-20250417130911-3f050ff8c56d'
    hash = 'sha256-BIJYTHJBA/3H6kudOzv2f3jBq2fgC6w0Wq7uW8w9Ge0='

  [mod.'github.com/mewpkg/term']
    version = 'v0.0.0-20241026122259-37a80af23985'
    hash = 'sha256-WgvLJUMIXdYgpZivX38fZqaMTIimnpLdpRVsBhjEWZI='

  [mod.'github.com/muesli/cancelreader']
    version = 'v0.2.2'
    hash = 'sha256-uEPpzwRJBJsQWBw6M71FDfgJuR7n55d/7IV8MO+rpwQ='

  [mod.'github.com/muesli/reflow']
    version = 'v0.3.0'
    hash = 'sha256-Pou2ybE9SFSZG6YfZLVV1Eyfm+X4FuVpDPLxhpn47Cc='

  [mod.'github.com/muesli/termenv']
    version = 'v0.16.0'
    hash = 'sha256-hGo275DJlyLtcifSLpWnk8jardOksdeX9lH4lBeE3gI='

  [mod.'github.com/nwaples/rardecode/v2']
    version = 'v2.2.2'
    hash = 'sha256-6PC/z/iDiuAq/UcA/EI0gV3gZiRBhoge9NKIU4hiiMQ='

  [mod.'github.com/pelletier/go-toml/v2']
    version = 'v2.3.1'
    hash = 'sha256-5H8+UOtPOs+Yc+8oVT/3bugCCdbq3jFMH6eOW8dadyg='

  [mod.'github.com/peterebden/ar']
    version = 'v0.0.0-20241106141004-20dc11b778e8'
    hash = 'sha256-zu6FAr/1RQKBa4qUJOLtNKRbc8HKqupdoh+PmsMpcBc='

  [mod.'github.com/pierrec/lz4/v4']
    version = 'v4.1.26'
    hash = 'sha256-fAdBNvKrB6vc9eYjGijgY0AxTE8sx4KIr+zDxKsHOws='

  [mod.'github.com/pmezard/go-difflib']
    version = 'v1.0.1-0.20181226105442-5d4384ee4fb2'
    hash = 'sha256-XA4Oj1gdmdV/F/+8kMI+DBxKPthZ768hbKsO3d9Gx90='

  [mod.'github.com/power-devops/perfstat']
    version = 'v0.0.0-20240221224432-82ca36839d55'
    hash = 'sha256-ujzuJ1ttQgjHQJEij4O/2+I8DZaUVZQCQgA4ysfqulI='

  [mod.'github.com/reinhrst/fzf-lib']
    version = 'v0.9.0'
    hash = 'sha256-UUe5g+oXopDj+JjvzAguqJ70/a4pqZhn7pdJiFE97yI='

  [mod.'github.com/rivo/uniseg']
    version = 'v0.4.7'
    hash = 'sha256-rDcdNYH6ZD8KouyyiZCUEy8JrjOQoAkxHBhugrfHjFo='

  [mod.'github.com/rwcarlsen/goexif']
    version = 'v0.0.0-20190401172101-9e8deecbddbd'
    hash = 'sha256-AiY2T9hXj6jnfldYDoe4WNr3FldpVTxc3lScR++HOLc='

  [mod.'github.com/saintfish/chardet']
    version = 'v0.0.0-20230101081208-5e3ef4b5456d'
    hash = 'sha256-JXlHMCbXB8iRQ9wQBGCeTjDSfgaBwUVOpvcjj0iVn5A='

  [mod.'github.com/shirou/gopsutil/v4']
    version = 'v4.26.5'
    hash = 'sha256-ODPWgxRHQqlARId7n9Crvpgiv54YFr96PnqZg+IAWpI='

  [mod.'github.com/spf13/afero']
    version = 'v1.15.0'
    hash = 'sha256-LhcezbOqfuBzacytbqck0hNUxi6NbWNhifUc5/9uHQ8='

  [mod.'github.com/sshaman1101/dcompress']
    version = 'v0.0.0-20200109162717-50436a6332de'
    hash = 'sha256-2diETNbHoHg9BjJqHXm4IoPGxazKD6h0FWhuFcW9emk='

  [mod.'github.com/stretchr/testify']
    version = 'v1.11.1'
    hash = 'sha256-sWfjkuKJyDllDEtnM8sb/pdLzPQmUYWYtmeWz/5suUc='

  [mod.'github.com/therootcompany/xz']
    version = 'v1.0.1'
    hash = 'sha256-SujtLzRINpXKEyldKuRYrTfhsLLop12PpdlY0F18/88='

  [mod.'github.com/ulikunitz/xz']
    version = 'v0.5.15'
    hash = 'sha256-L5KYLue5U14bxUuNyhZ6lIjbda6eCQsx1V6gToqfRdk='

  [mod.'github.com/urfave/cli/v3']
    version = 'v3.9.0'
    hash = 'sha256-G7F0o+VGex6fg68e9VH7EqvtSRRm5TZepZlhHWtPVP0='

  [mod.'github.com/xo/terminfo']
    version = 'v0.0.0-20220910002029-abceb7e1c41e'
    hash = 'sha256-GyCDxxMQhXA3Pi/TsWXpA8cX5akEoZV7CFx4RO3rARU='

  [mod.'github.com/yorukot/ansichroma']
    version = 'v0.1.0'
    hash = 'sha256-aIQZ16auuGfGLltKt2lm2T83f4sALrmRpOujxQepkS4='

  [mod.'github.com/yusufpapurcu/wmi']
    version = 'v1.2.4'
    hash = 'sha256-N+YDBjOW59YOsZ2lRBVtFsEEi48KhNQRb63/0ZSU3bA='

  [mod.'go4.org']
    version = 'v0.0.0-20260112195520-a5071408f32f'
    hash = 'sha256-K2sBsO4B4NwY2Hd5Do/LikhpvbL2prHh7cmOSvnTLrM='

  [mod.'golang.org/x/crypto']
    version = 'v0.48.0'
    hash = 'sha256-uBIGGSGmWWklRxX6XTOqUECzz165UFY9Y99Ka3pLKAw='

  [mod.'golang.org/x/image']
    version = 'v0.38.0'
    hash = 'sha256-YxgdnBfazaQiopq2rlJsGR7BbuaQF1hpeoWZhER8v9E='

  [mod.'golang.org/x/mod']
    version = 'v0.37.0'
    hash = 'sha256-dspScRv3KO4nytvjavhNO2b03P4UtiJQyWVGuEy9OUk='

  [mod.'golang.org/x/sync']
    version = 'v0.21.0'
    hash = 'sha256-2n7PVb1krz7UpnXYGVmCrxV0fZBnjQdVVt6eVudEPYY='

  [mod.'golang.org/x/sys']
    version = 'v0.43.0'
    hash = 'sha256-aDQXqSTZES2l/132PBxhZN4ywldpPyfm7LByYCHzzwM='

  [mod.'golang.org/x/text']
    version = 'v0.39.0'
    hash = 'sha256-jQR8eNeC6HIFxRdEbF3EAUcoCOvpSJ/latXSqt5w0YA='

  [mod.'golift.io/udf']
    version = 'v0.0.1'
    hash = 'sha256-VWIQAU1BJljMdZvz+3WSGRD1bHqZRSCpQHE2WWg5a3M='

  [mod.'golift.io/xtractr']
    version = 'v0.3.1'
    hash = 'sha256-EZhTUreeUL+mqrS0nF3Bk380XqimP7GcwG9FYbAVN8Q='

  [mod.'gopkg.in/yaml.v3']
    version = 'v3.0.1'
    hash = 'sha256-FqL9TKYJ0XkNwJFnq9j0VvJ5ZUU1RvH/52h/f5bkYAU='
