package components

/*
THESE CODE BASE ON https://github.com/acarl005/ls-go
thanks for the great work!!
*/

import (
	"path/filepath"
	"strings"
)

func getElementIcon(file string, IsDir bool) iconStyle {
	ext := strings.TrimPrefix(filepath.Ext(file), ".")
	name := file

	if IsDir {
		icon := folders["folder"]
		betterIcon, hasBetterIcon := folders[name]
		if hasBetterIcon {
			icon = betterIcon
		}
		return icon
	} else {
		// default icon for all files. try to find a better one though...
		icon := icons["file"]
		// resolve aliased extensions
		extKey := strings.ToLower(ext)
		alias, hasAlias := aliases[extKey]
		if hasAlias {
			extKey = alias
		}

		// see if we can find a better icon based on extension alone
		betterIcon, hasBetterIcon := icons[extKey]
		if hasBetterIcon {
			icon = betterIcon
		}

		// now look for icons based on full names
		fullName := name

		fullName = strings.ToLower(fullName)
		fullAlias, hasFullAlias := aliases[fullName]
		if hasFullAlias {
			fullName = fullAlias
		}
		bestIcon, hasBestIcon := icons[fullName]
		if hasBestIcon {
			icon = bestIcon
		}
		if icon.color == "NONE" {
			return iconStyle{
				icon:  icon.icon,
				color: "#E5C287",
			}
		}
		return icon
	}
}

var icons = map[string]iconStyle{
	"ai": {
		icon:  "",
		color: "#ce6f14",
	},
	"android":      {icon: "", color: "#a7c83f"},
	"apple":        {icon: "", color: "#78909c"},
	"asm":          {icon: "󰘚", color: "#ff7844"},
	"audio":        {icon: "", color: "#ee524f"},
	"binary":       {icon: "", color: "#ff7844"},
	"c":            {icon: "", color: "#0188d2"},
	"cfg":          {icon: "", color: "#8B8B8B"},
	"clj":          {icon: "", color: "#68b338"},
	"conf":         {icon: "", color: "#8B8B8B"},
	"cpp":          {icon: "", color: "#0188d2"},
	"css":          {icon: "", color: "#2d53e5"},
	"dart":         {icon: "", color: "#03589b"},
	"db":           {icon: "", color: "#FF8400"},
	"deb":          {icon: "", color: "#ab0836"},
	"doc":          {icon: "", color: "#295394"},
	"dockerfile":   {icon: "󰡨", color: "#099cec"},
	"ebook":        {icon: "", color: "#67b500"},
	"env":          {icon: "", color: "#eed645"},
	"f":            {icon: "󱈚", color: "NONE"},
	"file":         {icon: "\uf15b", color: "NONE"},
	"font":         {icon: "\uf031", color: "NONE"},
	"fs":           {icon: "\ue7a7", color: "NONE"},
	"gb":           {icon: "\ue272", color: "NONE"},
	"gform":        {icon: "\uf298", color: "NONE"},
	"git":          {icon: "\ue702", color: "NONE"},
	"go":           {icon: "", color: "NONE"},
	"graphql":      {icon: "\ue662", color: "NONE"},
	"glp":          {icon: "󰆧", color: "NONE"},
	"groovy":       {icon: "\ue775", color: "NONE"},
	"gruntfile.js": {icon: "\ue74c", color: "NONE"},
	"gulpfile.js":  {icon: "\ue610", color: "NONE"},
	"gv":           {icon: "\ue225", color: "NONE"},
	"h":            {icon: "\uf0fd", color: "NONE"},
	"haml":         {icon: "\ue664", color: "NONE"},
	"hs":           {icon: "\ue777", color: "NONE"},
	"html":         {icon: "\uf13b", color: "NONE"},
	"hx":           {icon: "\ue666", color: "NONE"},
	"ics":          {icon: "\uf073", color: "NONE"},
	"image":        {icon: "\uf1c5", color: "NONE"},
	"iml":          {icon: "\ue7b5", color: "NONE"},
	"ini":          {icon: "󰅪", color: "NONE"},
	"ino":          {icon: "\ue255", color: "NONE"},
	"iso":          {icon: "󰋊", color: "NONE"},
	"jade":         {icon: "\ue66c", color: "NONE"},
	"java":         {icon: "\ue738", color: "NONE"},
	"jenkinsfile":  {icon: "\ue767", color: "NONE"},
	"jl":           {icon: "\ue624", color: "NONE"},
	"js":           {icon: "\ue781", color: "NONE"},
	"json":         {icon: "\ue60b", color: "NONE"},
	"jsx":          {icon: "\ue7ba", color: "NONE"},
	"key":          {icon: "\uf43d", color: "NONE"},
	"ko":           {icon: "\uebc6", color: "NONE"},
	"kt":           {icon: "\ue634", color: "NONE"},
	"less":         {icon: "\ue758", color: "NONE"},
	"lock":         {icon: "\uf023", color: "NONE"},
	"log":          {icon: "\uf18d", color: "NONE"},
	"lua":          {icon: "\ue620", color: "NONE"},
	"maintainers":  {icon: "\uf0c0", color: "NONE"},
	"makefile":     {icon: "\ue20f", color: "NONE"},
	"md":           {icon: "\uf48a", color: "NONE"},
	"mjs":          {icon: "\ue718", color: "NONE"},
	"ml":           {icon: "󰘧", color: "NONE"},
	"mustache":     {icon: "\ue60f", color: "NONE"},
	"nc":           {icon: "󰋁", color: "NONE"},
	"nim":          {icon: "\ue677", color: "NONE"},
	"nix":          {icon: "\uf313", color: "NONE"},
	"npmignore":    {icon: "\ue71e", color: "NONE"},
	"package":      {icon: "󰏗", color: "NONE"},
	"passwd":       {icon: "\uf023", color: "NONE"},
	"patch":        {icon: "\uf440", color: "NONE"},
	"pdf":          {icon: "\uf1c1", color: "NONE"},
	"php":          {icon: "\ue608", color: "NONE"},
	"pl":           {icon: "\ue7a1", color: "NONE"},
	"prisma":       {icon: "\ue684", color: "NONE"},
	"ppt":          {icon: "\uf1c4", color: "NONE"},
	"psd":          {icon: "\ue7b8", color: "NONE"},
	"py":           {icon: "\ue606", color: "NONE"},
	"r":            {icon: "\ue68a", color: "NONE"},
	"rb":           {icon: "\ue21e", color: "NONE"},
	"rdb":          {icon: "\ue76d", color: "NONE"},
	"rpm":          {icon: "\uf17c", color: "NONE"},
	"rs":           {icon: "\ue7a8", color: "NONE"},
	"rss":          {icon: "\uf09e", color: "NONE"},
	"rst":          {icon: "󰅫", color: "NONE"},
	"rubydoc":      {icon: "\ue73b", color: "NONE"},
	"sass":         {icon: "\ue603", color: "NONE"},
	"scala":        {icon: "\ue737", color: "NONE"},
	"shell":        {icon: "\uf489", color: "NONE"},
	"shp":          {icon: "󰙞", color: "NONE"},
	"sol":          {icon: "󰡪", color: "NONE"},
	"sqlite":       {icon: "\ue7c4", color: "NONE"},
	"styl":         {icon: "\ue600", color: "NONE"},
	"svelte":       {icon: "\ue697", color: "NONE"},
	"swift":        {icon: "\ue755", color: "NONE"},
	"tex":          {icon: "\u222b", color: "NONE"},
	"tf":           {icon: "\ue69a", color: "NONE"},
	"toml":         {icon: "󰅪", color: "NONE"},
	"ts":           {icon: "󰛦", color: "NONE"},
	"twig":         {icon: "\ue61c", color: "NONE"},
	"txt":          {icon: "\uf15c", color: "NONE"},
	"vagrantfile":  {icon: "\ue21e", color: "NONE"},
	"video":        {icon: "\uf03d", color: "NONE"},
	"vim":          {icon: "\ue62b", color: "NONE"},
	"vue":          {icon: "\ue6a0", color: "NONE"},
	"windows":      {icon: "\uf17a", color: "NONE"},
	"xls":          {icon: "\uf1c3", color: "NONE"},
	"xml":          {icon: "\ue796", color: "NONE"},
	"yml":          {icon: "\ue601", color: "NONE"},
	"zig":          {icon: "\ue6a9", color: "NONE"},
	"zip":          {icon: "\uf410", color: "NONE"},
}

var aliases = map[string]string{
	"dart":             "dart",
	"apk":              "android",
	"gradle":           "android",
	"ds_store":         "apple",
	"localized":        "apple",
	"m":                "apple",
	"mm":               "apple",
	"s":                "asm",
	"aac":              "audio",
	"alac":             "audio",
	"flac":             "audio",
	"m4a":              "audio",
	"mka":              "audio",
	"mp3":              "audio",
	"ogg":              "audio",
	"opus":             "audio",
	"wav":              "audio",
	"wma":              "audio",
	"bson":             "binary",
	"feather":          "binary",
	"mat":              "binary",
	"o":                "binary",
	"pb":               "binary",
	"pickle":           "binary",
	"pkl":              "binary",
	"tfrecord":         "binary",
	"conf":             "cfg",
	"config":           "cfg",
	"cljc":             "clj",
	"cljs":             "clj",
	"editorconfig":     "conf",
	"rc":               "conf",
	"c++":              "cpp",
	"cc":               "cpp",
	"cxx":              "cpp",
	"scss":             "css",
	"sql":              "db",
	"docx":             "doc",
	"gdoc":             "doc",
	"dockerignore":     "dockerfile",
	"epub":             "ebook",
	"ipynb":            "ebook",
	"mobi":             "ebook",
	"env":              "env",
	".env.local":       "env",
	"local":            "env",
	"f03":              "f",
	"f77":              "f",
	"f90":              "f",
	"f95":              "f",
	"for":              "f",
	"fpp":              "f",
	"ftn":              "f",
	"eot":              "font",
	"otf":              "font",
	"ttf":              "font",
	"woff":             "font",
	"woff2":            "font",
	"fsi":              "fs",
	"fsscript":         "fs",
	"fsx":              "fs",
	"dna":              "gb",
	"gitattributes":    "git",
	"gitconfig":        "git",
	"gitignore":        "git",
	"gitignore_global": "git",
	"gitmirrorall":     "git",
	"gitmodules":       "git",
	"gltf":             "glp",
	"gsh":              "groovy",
	"gvy":              "groovy",
	"gy":               "groovy",
	"h++":              "h",
	"hh":               "h",
	"hpp":              "h",
	"hxx":              "h",
	"lhs":              "hs",
	"htm":              "html",
	"xhtml":            "html",
	"bmp":              "image",
	"cbr":              "image",
	"cbz":              "image",
	"dvi":              "image",
	"eps":              "image",
	"gif":              "image",
	"ico":              "image",
	"jpeg":             "image",
	"jpg":              "image",
	"nef":              "image",
	"orf":              "image",
	"pbm":              "image",
	"pgm":              "image",
	"png":              "image",
	"pnm":              "image",
	"ppm":              "image",
	"pxm":              "image",
	"sixel":            "image",
	"stl":              "image",
	"svg":              "image",
	"tif":              "image",
	"tiff":             "image",
	"webp":             "image",
	"xpm":              "image",
	"disk":             "iso",
	"dmg":              "iso",
	"img":              "iso",
	"ipsw":             "iso",
	"smi":              "iso",
	"vhd":              "iso",
	"vhdx":             "iso",
	"vmdk":             "iso",
	"jar":              "java",
	"cjs":              "js",
	"properties":       "json",
	"webmanifest":      "json",
	"tsx":              "jsx",
	"cjsx":             "jsx",
	"cer":              "key",
	"crt":              "key",
	"der":              "key",
	"gpg":              "key",
	"p7b":              "key",
	"pem":              "key",
	"pfx":              "key",
	"pgp":              "key",
	"license":          "key",
	"codeowners":       "maintainers",
	"credits":          "maintainers",
	"cmake":            "makefile",
	"justfile":         "makefile",
	"markdown":         "md",
	"mkd":              "md",
	"rdoc":             "md",
	"readme":           "md",
	"mli":              "ml",
	"sml":              "ml",
	"netcdf":           "nc",
	"brewfile":         "package",
	"cargo.toml":       "package",
	"cargo.lock":       "package",
	"go.mod":           "package",
	"go.sum":           "package",
	"pyproject.toml":   "package",
	"poetry.lock":      "package",
	"package.json":     "package",
	"pipfile":          "package",
	"pipfile.lock":     "package",
	"php3":             "php",
	"php4":             "php",
	"php5":             "php",
	"phpt":             "php",
	"phtml":            "php",
	"gslides":          "ppt",
	"pptx":             "ppt",
	"pxd":              "py",
	"pyc":              "py",
	"pyx":              "py",
	"whl":              "py",
	"rdata":            "r",
	"rds":              "r",
	"rmd":              "r",
	"gemfile":          "rb",
	"gemspec":          "rb",
	"guardfile":        "rb",
	"procfile":         "rb",
	"rakefile":         "rb",
	"rspec":            "rb",
	"rspec_parallel":   "rb",
	"rspec_status":     "rb",
	"ru":               "rb",
	"erb":              "rubydoc",
	"slim":             "rubydoc",
	"awk":              "shell",
	"bash":             "shell",
	"bash_history":     "shell",
	"bash_profile":     "shell",
	"bashrc":           "shell",
	"csh":              "shell",
	"fish":             "shell",
	"ksh":              "shell",
	"sh":               "shell",
	"zsh":              "shell",
	"zsh-theme":        "shell",
	"zshrc":            "shell",
	"plpgsql":          "sql",
	"plsql":            "sql",
	"psql":             "sql",
	"tsql":             "sql",
	"sl3":              "sqlite",
	"sqlite3":          "sqlite",
	"stylus":           "styl",
	"cls":              "tex",
	"avi":              "video",
	"flv":              "video",
	"m2v":              "video",
	"mkv":              "video",
	"mov":              "video",
	"mp4":              "video",
	"mpeg":             "video",
	"mpg":              "video",
	"ogm":              "video",
	"ogv":              "video",
	"vob":              "video",
	"webm":             "video",
	"vimrc":            "vim",
	"bat":              "windows",
	"cmd":              "windows",
	"exe":              "windows",
	"csv":              "xls",
	"gsheet":           "xls",
	"xlsx":             "xls",
	"plist":            "xml",
	"xul":              "xml",
	"yaml":             "yml",
	"7z":               "zip",
	"Z":                "zip",
	"bz2":              "zip",
	"gz":               "zip",
	"lzma":             "zip",
	"par":              "zip",
	"rar":              "zip",
	"tar":              "zip",
	"tc":               "zip",
	"tgz":              "zip",
	"txz":              "zip",
	"xz":               "zip",
	"z":                "zip",
}

var folders = map[string]iconStyle{
	".atom":                 {icon: "\ue764", color: "NONE"},
	".aws":                  {icon: "\ue7ad", color: "NONE"},
	".docker":               {icon: "\ue7b0", color: "NONE"},
	".gem":                  {icon: "\ue21e", color: "NONE"},
	".git":                  {icon: "\ue5fb", color: "NONE"},
	".git-credential-cache": {icon: "\ue5fb", color: "NONE"},
	".github":               {icon: "\ue5fd", color: "NONE"},
	".npm":                  {icon: "\ue5fa", color: "NONE"},
	".nvm":                  {icon: "\ue718", color: "NONE"},
	".rvm":                  {icon: "\ue21e", color: "NONE"},
	".Trash":                {icon: "\uf1f8", color: "NONE"},
	".vscode":               {icon: "\ue70c", color: "NONE"},
	".vim":                  {icon: "\ue62b", color: "NONE"},
	"config":                {icon: "\ue5fc", color: "NONE"},
	"folder":                {icon: "", color: "NONE"},
	"hidden":                {icon: "\uf023", color: "NONE"},
	"node_modules":          {icon: "\ue5fa", color: "NONE"},
}
