name: Mirror to Codeberg
permissions:
  contents: read

on: [push]  # Trigger on push to ANY branch

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - uses: yesolutions/mirror-action@master
        with:
          REMOTE: 'https://codeberg.org/yorukot/superfile.git'
          GIT_USERNAME: yorukot
          GIT_PASSWORD: ${{ secrets.CODEBERG_TOKEN }}
          PUSH_ALL_REFS: "true"