name: Publish to WinGet

on:
  release:
    types: [published]

jobs:
  winget:
    name: Publish WinGet package
    runs-on: ubuntu-latest
    steps:
      - name: Submit package to Windows Package Manager Community Repository
        uses: vedantmgoyal2009/winget-releaser@v2
        with:
          identifier: yorukot.superfile
          installers-regex: '\.zip$'
          version: ${{ github.event.release.tag_name }}
          release-tag: ${{ github.event.release.tag_name }}
          token: ${{ secrets.WINGET_TOKEN }} 